### ISSUE TITLE
Support object as first argument when defining methods for a Route 

### ISSUE THREAD

**Issue by dsalin** [ukayani/restify-router#13]
Currently, a **`string`** is used as first argument to any Route method (get, put, post, etc.)
This prevents us from supplying **`version`** and other parameters to a route (or at least I have not found a way in current version of **restify-router**).

Please, add this feature or tell me if you encourage PRs. I'll try to do my best in this case :)

**Comment by ukayani** [comment]
Hi @dsalin . PRs are definitely welcome :) If not, i'll look into making the change.

**Comment by ukayani** [comment]
Actually, @dsalin after further looking at your comment. I believe we do support this behavior

**Comment by dsalin** [comment]
Thank you very much @ukayani. Yes, this is what I was looking for.
