### ISSUE TITLE
Use joi with restify-router

### ISSUE THREAD

**Issue by tsghosh** [ukayani/restify-router#14]
I am trying to add a validation using joi like this

sme.get('/country/:country/state/:state/city/:city',_**validator**_, function(req, res, next) {
})

Can you please comment if it is possible to use joi adaptor like restify-joi-middleware
with restify-router

thanks
tuhin

**Comment by ukayani** [comment]
Hi @tsghosh ,

Yes, it is possible. You can use the exact same interface as the restify server.

```javascript

const sme = new Router();
sme.get('/country/:country/state/:state/city/:city', **validator**, function(req, res, next) {
});

sme.applyRoutes(server);
```

**Comment by tsghosh** [comment]
Thanks.
