### ISSUE TITLE
Data in body is not parsed

### ISSUE THREAD

**Issue by danysz** [ukayani/restify-router#18]
I am sending the body as a JSON and I put the relevant plugins in restify

When I add the "testify-routes" the req.params is not parsing the body of the request so I am not able to use them

Regards

**Comment by ukayani** [comment]
@danysz

Could you please provide a code example of what you are trying to do that doesn’t work?

If you take a look at the tests, you may find a similar scenario as you are trying to accomplish.

**Comment by danysz** [comment]
it looks that is my mistake.
now it's working.
really strange
