### ISSUE TITLE
Using restify-validations-engine

### ISSUE THREAD

**Issue by Pritoj** [ukayani/restify-router#19]
I want to use [this validation engine](https://github.com/paulvarache/restify-validation-engine), however I can't seem to figure out where to add the validate option.

Its supposed to be added like this. Any help will be much appreciated.

```
server.get({
    url: '/my-url',
    validate: { // Entry point of the module
        params: { // Which scope
            myParam: { // The field to validate
                required: true // A validator
            }
        }
    }
});

```

**Comment by ukayani** [comment]
Hi,
That plugin seems to have added a top level property to the route object. I can take a look at the plugin and see if its possible. I may need to make a small adjustment to the code

**Comment by Pritoj** [comment]
Hey,
Actually, the problem is with that plugin. It doesn't work with version 6 I think. So it should be okay. Please feel free to go ahead and close this issue.

Thanks

**Comment by ukayani** [comment]
Thanks
