### ISSUE TITLE
Allow to pass custom middlewares when applying routes

### ISSUE THREAD

**Issue by anhnt** [ukayani/restify-router#3]
Something like:
```
require('./app/routers/product.router').applyRoutes(server, '/api/v1', [middleWareFunctions]);
```

**Comment by ukayani** [comment]
Hi, thanks for the suggestion.

From what I understand, you'd like to have the middle ware functions be applied for every route defined in the Router instance?

 I'll look into how to incorporate this feature into the component over the weekend. If you would like to provide an implementation, feel free to fork and create a pull request.

**Comment by anhnt** [comment]
Thanks for your quick reply. I'd like to have a feature that allows applying middlewares for each route as well as Router instance level. That should be very helpful :) Appreciate your work, well done :)

**Comment by ukayani** [comment]
Hi, I've created a branch called `feature/middleware`. Please take a look at the changes and let me know if this is what you were asking for.

Changes:
- Added a method to Router called `use`

```javascript
var router = new Router();
router.use(function (req, res, next) {
   req.user = 'bob';
   next();
});
router.get('/hello', function (req, res, next) {
   res.send('Hello ' + req.user);
   next();
});

router.get('/test', function (req, res, next) {
   res.send('Test ' + req.user);
   next();  
});

router.applyRoutes(server);

// calling GET /hello  runs use middle ware first and then the routes middleware

```

Essentially the method behaves like the restify server use method for common middleware except it only applies the middleware to the registered routes for the router.

I'll need to add some tests and then cut a release.

**Comment by ukayani** [comment]
@anhnt  I've merged the changes in. v0.3. It should be available in the NPM registry. Please let me know if you have any issues. Thanks.

**Comment by anhnt** [comment]
Thanks @ukayani i will check and get back to you soon. Merry Christmas :)

**Comment by anhnt** [comment]
Just tested and it worked great. Cheers

**Comment by ukayani** [comment]
Cheers. Merry Christmas to you as well.
